# Generated by Django 4.1.4 on 2023-01-16 21:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Estacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                ("code", models.CharField(max_length=50, verbose_name="Código")),
            ],
            options={
                "verbose_name": "Estacion",
                "verbose_name_plural": "Estaciones",
            },
        ),
        migrations.CreateModel(
            name="Provincia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Provincia")),
            ],
            options={
                "verbose_name": "Provincia",
                "verbose_name_plural": "Provincias",
            },
        ),
        migrations.CreateModel(
            name="Synop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("synop_code", models.TextField(verbose_name="Código Synop")),
                (
                    "tipo_synop",
                    models.CharField(
                        default="AAXX", max_length=250, verbose_name="Tipo de Synop"
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha")),
                ("hora", models.IntegerField(default=0, verbose_name="Hora UTC")),
                (
                    "indicador_viento_Iw",
                    models.CharField(
                        default="No proporcionado",
                        max_length=250,
                        verbose_name="Indicador del Viento",
                    ),
                ),
                (
                    "var_IIiii",
                    models.CharField(
                        default="No proporcionado",
                        max_length=250,
                        verbose_name="Indicativo internacional de la estación",
                    ),
                ),
                (
                    "var_IIiii_code",
                    models.CharField(
                        default="No proporcionado",
                        max_length=250,
                        verbose_name="Código de la Estación",
                    ),
                ),
                (
                    "var_Iy",
                    models.CharField(
                        default="No proporcionado",
                        max_length=250,
                        verbose_name="Inclusión u omisión de precipitación",
                    ),
                ),
                (
                    "var_Ix",
                    models.CharField(
                        default="No proporcionado",
                        max_length=250,
                        verbose_name="Tipo de operación de la estación",
                    ),
                ),
                (
                    "var_H",
                    models.CharField(
                        default="No proporcionado",
                        max_length=250,
                        verbose_name="Altura por encima del suelo",
                    ),
                ),
                (
                    "var_VV",
                    models.CharField(
                        default="No proporcionado",
                        max_length=250,
                        verbose_name="Visibilidad horizontal en superficie",
                    ),
                ),
                (
                    "var_N",
                    models.CharField(
                        default="No proporcionado",
                        max_length=250,
                        verbose_name="Cobertura nubosa total en octavos",
                    ),
                ),
                (
                    "var_dd",
                    models.CharField(
                        default="No proporcionado",
                        max_length=250,
                        verbose_name="Dirección verdadera de donde sopla el viento en °",
                    ),
                ),
                (
                    "var_ff",
                    models.CharField(
                        default="No proporcionado",
                        max_length=50,
                        verbose_name="Velocidad del viento en nudos",
                    ),
                ),
                (
                    "var_direccion",
                    models.CharField(
                        default="No proporcionado",
                        max_length=250,
                        verbose_name="Dirección",
                    ),
                ),
                (
                    "vat_TTT",
                    models.FloatField(
                        default=-999, verbose_name="Tempertura del Aire en °C"
                    ),
                ),
                (
                    "var_TTT_rocio",
                    models.FloatField(
                        default=-999, verbose_name="Tempertura del Rocío en °C"
                    ),
                ),
                (
                    "var_UUU",
                    models.IntegerField(
                        default=-999, verbose_name="Humedad relativa en porcentaje"
                    ),
                ),
                (
                    "var_PPPP",
                    models.FloatField(
                        default=-999,
                        verbose_name="Presión a nivel de la estación en hPa",
                    ),
                ),
                (
                    "var_PPPP_mar",
                    models.FloatField(
                        default=-999, verbose_name="Presión a nivel medio del mar"
                    ),
                ),
                (
                    "var_a",
                    models.CharField(
                        default="No proporcionado",
                        max_length=250,
                        verbose_name="Característica de la tendencia barométricas",
                    ),
                ),
                (
                    "var_ppp",
                    models.FloatField(default=-999, verbose_name="Valor en hPa"),
                ),
                (
                    "var_RRR",
                    models.FloatField(
                        default=-999, verbose_name="Precipitaciones en mm"
                    ),
                ),
                (
                    "var_Tr",
                    models.CharField(
                        default="No proporcionado",
                        max_length=250,
                        verbose_name="Tiempo en el que a caido las Precipitaciones",
                    ),
                ),
                (
                    "var_ww_presente",
                    models.CharField(
                        default="No proporcionado",
                        max_length=250,
                        verbose_name="Tiempo presente desde una estación",
                    ),
                ),
                (
                    "var_WW_pasado",
                    models.CharField(
                        default="No proporcionado",
                        max_length=250,
                        verbose_name="Tiempo pasado desde una estación",
                    ),
                ),
                (
                    "var_CCC",
                    models.CharField(
                        default="No proporcionado",
                        max_length=400,
                        verbose_name="Cantidad de nubes",
                    ),
                ),
                (
                    "var_GGgg",
                    models.CharField(
                        default="No proporcionado",
                        max_length=250,
                        verbose_name="Hora con minutos",
                    ),
                ),
                (
                    "var_Cs",
                    models.CharField(
                        default="No proporcionado",
                        max_length=400,
                        verbose_name="Estado del cielo en los trópicos",
                    ),
                ),
                (
                    "var_TTT_maxima",
                    models.FloatField(
                        default=-999,
                        verbose_name="Temperatura máxima de las últimas 12 horas",
                    ),
                ),
                (
                    "var_TTT_minima",
                    models.FloatField(
                        default=-999,
                        verbose_name="Temperatura mínima de las últimas 12 horas",
                    ),
                ),
                (
                    "var_E",
                    models.CharField(
                        default="No proporcionado",
                        max_length=250,
                        verbose_name="Estado del suelo",
                    ),
                ),
                (
                    "var_TT_suelo",
                    models.FloatField(
                        default=-999,
                        verbose_name="Temperatura mínima del suelo  entre las 00 y 12 UTC",
                    ),
                ),
                (
                    "var_E_hielo",
                    models.CharField(
                        default="No proporcionado",
                        max_length=250,
                        verbose_name="Estado del suelo (nieve o con una capa de hielo medible)",
                    ),
                ),
                (
                    "var_sss",
                    models.CharField(
                        default="No proporcionado",
                        max_length=250,
                        verbose_name="Profundidad de la nieve",
                    ),
                ),
                (
                    "var_g0",
                    models.CharField(
                        default="No proporcionado",
                        max_length=250,
                        verbose_name="Número de horas enteras que han transcurrido desde el momento del cambio",
                    ),
                ),
                (
                    "var_dT",
                    models.CharField(
                        default="No proporcionado",
                        max_length=250,
                        verbose_name="Cambio de temperatura ",
                    ),
                ),
                (
                    "var_EEE_evapo",
                    models.FloatField(
                        default=-999, verbose_name="Cantidad de evaporación"
                    ),
                ),
                (
                    "var_iE",
                    models.CharField(
                        default="No proporcionado",
                        max_length=250,
                        verbose_name="Tipo de instrumento para medir la evaporación",
                    ),
                ),
                (
                    "var_SSS_insolacion",
                    models.FloatField(
                        default=-999, verbose_name="Horas diarias de insolación"
                    ),
                ),
                (
                    "var_Dl",
                    models.CharField(
                        default="No proporcionado",
                        max_length=250,
                        verbose_name="Dirección y movimiento de las nubes Cl",
                    ),
                ),
                (
                    "var_Dm",
                    models.CharField(
                        default="No proporcionado",
                        max_length=250,
                        verbose_name="Dirección y movimiento de las nubes Cm",
                    ),
                ),
                (
                    "var_Dh",
                    models.CharField(
                        default="No proporcionado",
                        max_length=250,
                        verbose_name="Dirección y movimiento de las nubes Ch",
                    ),
                ),
                (
                    "var_C_genero",
                    models.CharField(
                        default="No proporcionado",
                        max_length=250,
                        verbose_name="Género",
                    ),
                ),
                (
                    "var_D",
                    models.CharField(
                        default="No proporcionado",
                        max_length=250,
                        verbose_name="Dirección en la que se ven nubes",
                    ),
                ),
                (
                    "var_C_angulo",
                    models.CharField(
                        default="No proporcionado",
                        max_length=250,
                        verbose_name="Ángulo de elevación de la cima de la nube",
                    ),
                ),
                (
                    "var_PPP_presion",
                    models.FloatField(
                        default=-999,
                        verbose_name="Variación de la presión últimas 24 horas",
                    ),
                ),
                (
                    "var_RRR_presipitacion",
                    models.FloatField(
                        default=-999, verbose_name="Cantidad de precipitación acumulada"
                    ),
                ),
                (
                    "var_RRRR",
                    models.FloatField(
                        default=-999,
                        verbose_name="Precipitación 24 h antes de la observación en mm",
                    ),
                ),
                (
                    "var_N_nubes",
                    models.CharField(
                        default="No proporcionado",
                        max_length=250,
                        verbose_name="Cantidad de nubes individuales del género",
                    ),
                ),
                (
                    "var_C_nube",
                    models.CharField(
                        default="No proporcionado",
                        max_length=250,
                        verbose_name="Tipo de nubes",
                    ),
                ),
                (
                    "var_hhh",
                    models.CharField(
                        default="No proporcionado",
                        max_length=250,
                        verbose_name="Dirección en la que se ven nubes",
                    ),
                ),
                (
                    "var_PhPh",
                    models.CharField(
                        default="No proporcionado",
                        max_length=250,
                        verbose_name="QNH en hPa",
                    ),
                ),
                (
                    "var_CCCC",
                    models.CharField(
                        default="No hay cenizas volcánicas",
                        max_length=250,
                        verbose_name="Presencia de cenizas volcánicas",
                    ),
                ),
                (
                    "var_FFFF",
                    models.IntegerField(
                        default=-999, verbose_name="Nivel de la capa freática"
                    ),
                ),
                (
                    "var_EEEE",
                    models.FloatField(default=-999, verbose_name="Evaporación diaria"),
                ),
                (
                    "var_dxdx",
                    models.CharField(
                        default="No proporcionado",
                        max_length=250,
                        verbose_name="Dirección de la ráfaga",
                    ),
                ),
                (
                    "var_fxfx",
                    models.CharField(
                        default="No proporcionado",
                        max_length=250,
                        verbose_name="Velocidad en nudos de la ráfaga",
                    ),
                ),
                (
                    "var_HeHeHe",
                    models.CharField(
                        default="No proporcionado",
                        max_length=250,
                        verbose_name="Heliofanía efectiva del día civil anterior",
                    ),
                ),
                (
                    "var_Iv",
                    models.CharField(
                        default="No proporcionado",
                        max_length=250,
                        verbose_name=" Tipo de instrumento medidor de viento",
                    ),
                ),
                (
                    "var_HHH_max",
                    models.CharField(
                        default="No proporcionado",
                        max_length=250,
                        verbose_name="Horas en que se registraron las temperaturas máximas",
                    ),
                ),
                (
                    "var_HHH_min",
                    models.CharField(
                        default="No proporcionado",
                        max_length=250,
                        verbose_name="Horas en que se registraron las temperatura mínimas",
                    ),
                ),
                (
                    "var_TTT_pos",
                    models.CharField(
                        default="No proporcionado",
                        max_length=250,
                        verbose_name="Temperatura del suelo de cero grados o mayor",
                    ),
                ),
                (
                    "var_HHH_neg",
                    models.CharField(
                        default="No proporcionado",
                        max_length=250,
                        verbose_name="Temperatura del suelo inferior a cero grados",
                    ),
                ),
                (
                    "var_dd_ff",
                    models.CharField(
                        default="No proporcionado",
                        max_length=250,
                        verbose_name="Dirección desde la que sopló la ráfaga - Velocidad",
                    ),
                ),
                (
                    "var_HHH_rafaga",
                    models.CharField(
                        default="No proporcionado",
                        max_length=250,
                        verbose_name="Hora de ocurrencia de la ráfaga",
                    ),
                ),
                (
                    "var_HmHmHnHn",
                    models.CharField(
                        default="No proporcionado",
                        max_length=250,
                        verbose_name="Valor de la humedad y minima en %",
                    ),
                ),
                (
                    "var_RRR_semana",
                    models.FloatField(
                        default=-999, verbose_name="Precipitaciones de la semana en mm"
                    ),
                ),
                (
                    "estacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tiempo.estacion",
                        verbose_name="Estacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Synop",
                "verbose_name_plural": "Synops",
            },
        ),
        migrations.CreateModel(
            name="Pronostico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha")),
                ("n_temp_min", models.IntegerField(verbose_name="Mañana (Mín)")),
                ("n_temp_max", models.IntegerField(verbose_name="Mañana (Máx)")),
                ("n_temp_tarde_min", models.IntegerField(verbose_name="Tarde (Mín)")),
                ("n_temp_tarde_max", models.IntegerField(verbose_name="Tarde (Máx)")),
                ("n_temp_noche_min", models.IntegerField(verbose_name="Noche (Mín)")),
                ("n_temp_noche_max", models.IntegerField(verbose_name="Noche (Máx)")),
                ("i_temp_min", models.IntegerField(verbose_name="Mañana (Mín)")),
                ("i_temp_max", models.IntegerField(verbose_name="Mañana (Máx)")),
                ("i_temp_tarde_min", models.IntegerField(verbose_name="Tarde (Mín)")),
                ("i_temp_tarde_max", models.IntegerField(verbose_name="Tarde (Máx)")),
                ("i_temp_noche_min", models.IntegerField(verbose_name="Noche (Mín)")),
                ("i_temp_noche_max", models.IntegerField(verbose_name="Noche (Máx)")),
                ("s_temp_min", models.IntegerField(verbose_name="Mañana (Mín)")),
                ("s_temp_max", models.IntegerField(verbose_name="Mañana (Máx)")),
                ("s_temp_tarde_min", models.IntegerField(verbose_name="Tarde (Mín)")),
                ("s_temp_tarde_max", models.IntegerField(verbose_name="Tarde (Máx)")),
                ("s_temp_noche_min", models.IntegerField(verbose_name="Noche (Mín)")),
                ("s_temp_noche_max", models.IntegerField(verbose_name="Noche (Máx)")),
                (
                    "n_tiempo_tarde",
                    models.CharField(
                        choices=[
                            ("PN", "PN"),
                            ("PARCN", "PARCN"),
                            ("N", "N"),
                            ("AIS CHUB", "AIS CHUB"),
                            ("ALG CHUB", "ALG CHUB"),
                            ("NUM CHUB", "NUM CHUB"),
                            ("ALG TORM", "ALG TORM"),
                            ("NUM TORM", "NUM TORM"),
                        ],
                        max_length=250,
                        verbose_name="Tarde",
                    ),
                ),
                (
                    "n_tiempo_manana",
                    models.CharField(
                        choices=[
                            ("PN", "PN"),
                            ("PARCN", "PARCN"),
                            ("N", "N"),
                            ("AIS CHUB", "AIS CHUB"),
                            ("ALG CHUB", "ALG CHUB"),
                            ("NUM CHUB", "NUM CHUB"),
                            ("ALG TORM", "ALG TORM"),
                            ("NUM TORM", "NUM TORM"),
                        ],
                        max_length=250,
                        verbose_name="Mañana",
                    ),
                ),
                (
                    "n_tiempo_noche",
                    models.CharField(
                        choices=[
                            ("PN", "PN"),
                            ("PARCN", "PARCN"),
                            ("N", "N"),
                            ("AIS CHUB", "AIS CHUB"),
                            ("ALG CHUB", "ALG CHUB"),
                            ("NUM CHUB", "NUM CHUB"),
                            ("ALG TORM", "ALG TORM"),
                            ("NUM TORM", "NUM TORM"),
                        ],
                        max_length=250,
                        verbose_name="Noche",
                    ),
                ),
                (
                    "i_tiempo_tarde",
                    models.CharField(
                        choices=[
                            ("PN", "PN"),
                            ("PARCN", "PARCN"),
                            ("N", "N"),
                            ("AIS CHUB", "AIS CHUB"),
                            ("ALG CHUB", "ALG CHUB"),
                            ("NUM CHUB", "NUM CHUB"),
                            ("ALG TORM", "ALG TORM"),
                            ("NUM TORM", "NUM TORM"),
                        ],
                        max_length=250,
                        verbose_name="Tarde",
                    ),
                ),
                (
                    "i_tiempo_manana",
                    models.CharField(
                        choices=[
                            ("PN", "PN"),
                            ("PARCN", "PARCN"),
                            ("N", "N"),
                            ("AIS CHUB", "AIS CHUB"),
                            ("ALG CHUB", "ALG CHUB"),
                            ("NUM CHUB", "NUM CHUB"),
                            ("ALG TORM", "ALG TORM"),
                            ("NUM TORM", "NUM TORM"),
                        ],
                        max_length=250,
                        verbose_name="Mañana",
                    ),
                ),
                (
                    "i_tiempo_noche",
                    models.CharField(
                        choices=[
                            ("PN", "PN"),
                            ("PARCN", "PARCN"),
                            ("N", "N"),
                            ("AIS CHUB", "AIS CHUB"),
                            ("ALG CHUB", "ALG CHUB"),
                            ("NUM CHUB", "NUM CHUB"),
                            ("ALG TORM", "ALG TORM"),
                            ("NUM TORM", "NUM TORM"),
                        ],
                        max_length=250,
                        verbose_name="Noche",
                    ),
                ),
                (
                    "s_tiempo_tarde",
                    models.CharField(
                        choices=[
                            ("PN", "PN"),
                            ("PARCN", "PARCN"),
                            ("N", "N"),
                            ("AIS CHUB", "AIS CHUB"),
                            ("ALG CHUB", "ALG CHUB"),
                            ("NUM CHUB", "NUM CHUB"),
                            ("ALG TORM", "ALG TORM"),
                            ("NUM TORM", "NUM TORM"),
                        ],
                        max_length=250,
                        verbose_name="Tarde",
                    ),
                ),
                (
                    "s_tiempo_manana",
                    models.CharField(
                        choices=[
                            ("PN", "PN"),
                            ("PARCN", "PARCN"),
                            ("N", "N"),
                            ("AIS CHUB", "AIS CHUB"),
                            ("ALG CHUB", "ALG CHUB"),
                            ("NUM CHUB", "NUM CHUB"),
                            ("ALG TORM", "ALG TORM"),
                            ("NUM TORM", "NUM TORM"),
                        ],
                        max_length=250,
                        verbose_name="Mañana",
                    ),
                ),
                (
                    "s_tiempo_noche",
                    models.CharField(
                        choices=[
                            ("PN", "PN"),
                            ("PARCN", "PARCN"),
                            ("N", "N"),
                            ("AIS CHUB", "AIS CHUB"),
                            ("ALG CHUB", "ALG CHUB"),
                            ("NUM CHUB", "NUM CHUB"),
                            ("ALG TORM", "ALG TORM"),
                            ("NUM TORM", "NUM TORM"),
                        ],
                        max_length=250,
                        verbose_name="Noche",
                    ),
                ),
                (
                    "n_viento_dir_tarde",
                    models.CharField(
                        choices=[
                            ("VRB", "VRB"),
                            ("N", "N"),
                            ("NNE", "NNE"),
                            ("NE", "NE"),
                            ("ENE", "ENE"),
                            ("E", "E"),
                            ("ESE", "ESE"),
                            ("SE", "SE"),
                            ("SSE", "SSE"),
                            ("S", "S"),
                            ("SSW", "SSW"),
                            ("SW", "SW"),
                            ("WSW", "WSW"),
                            ("W", "W"),
                            ("WNW", "WNW"),
                            ("NW", "NW"),
                            ("NNW", "NNW"),
                        ],
                        default="VRB",
                        max_length=250,
                        verbose_name="Tarde",
                    ),
                ),
                (
                    "n_viento_dir_manana",
                    models.CharField(
                        choices=[
                            ("VRB", "VRB"),
                            ("N", "N"),
                            ("NNE", "NNE"),
                            ("NE", "NE"),
                            ("ENE", "ENE"),
                            ("E", "E"),
                            ("ESE", "ESE"),
                            ("SE", "SE"),
                            ("SSE", "SSE"),
                            ("S", "S"),
                            ("SSW", "SSW"),
                            ("SW", "SW"),
                            ("WSW", "WSW"),
                            ("W", "W"),
                            ("WNW", "WNW"),
                            ("NW", "NW"),
                            ("NNW", "NNW"),
                        ],
                        default="VRB",
                        max_length=250,
                        verbose_name="Mañana",
                    ),
                ),
                (
                    "n_viento_dir_noche",
                    models.CharField(
                        choices=[
                            ("VRB", "VRB"),
                            ("N", "N"),
                            ("NNE", "NNE"),
                            ("NE", "NE"),
                            ("ENE", "ENE"),
                            ("E", "E"),
                            ("ESE", "ESE"),
                            ("SE", "SE"),
                            ("SSE", "SSE"),
                            ("S", "S"),
                            ("SSW", "SSW"),
                            ("SW", "SW"),
                            ("WSW", "WSW"),
                            ("W", "W"),
                            ("WNW", "WNW"),
                            ("NW", "NW"),
                            ("NNW", "NNW"),
                        ],
                        default="VRB",
                        max_length=250,
                        verbose_name="Noche",
                    ),
                ),
                (
                    "i_viento_dir_tarde",
                    models.CharField(
                        choices=[
                            ("VRB", "VRB"),
                            ("N", "N"),
                            ("NNE", "NNE"),
                            ("NE", "NE"),
                            ("ENE", "ENE"),
                            ("E", "E"),
                            ("ESE", "ESE"),
                            ("SE", "SE"),
                            ("SSE", "SSE"),
                            ("S", "S"),
                            ("SSW", "SSW"),
                            ("SW", "SW"),
                            ("WSW", "WSW"),
                            ("W", "W"),
                            ("WNW", "WNW"),
                            ("NW", "NW"),
                            ("NNW", "NNW"),
                        ],
                        default="VRB",
                        max_length=250,
                        verbose_name="Tarde",
                    ),
                ),
                (
                    "i_viento_dir_manana",
                    models.CharField(
                        choices=[
                            ("VRB", "VRB"),
                            ("N", "N"),
                            ("NNE", "NNE"),
                            ("NE", "NE"),
                            ("ENE", "ENE"),
                            ("E", "E"),
                            ("ESE", "ESE"),
                            ("SE", "SE"),
                            ("SSE", "SSE"),
                            ("S", "S"),
                            ("SSW", "SSW"),
                            ("SW", "SW"),
                            ("WSW", "WSW"),
                            ("W", "W"),
                            ("WNW", "WNW"),
                            ("NW", "NW"),
                            ("NNW", "NNW"),
                        ],
                        default="VRB",
                        max_length=250,
                        verbose_name="Mañana",
                    ),
                ),
                (
                    "i_viento_dir_noche",
                    models.CharField(
                        choices=[
                            ("VRB", "VRB"),
                            ("N", "N"),
                            ("NNE", "NNE"),
                            ("NE", "NE"),
                            ("ENE", "ENE"),
                            ("E", "E"),
                            ("ESE", "ESE"),
                            ("SE", "SE"),
                            ("SSE", "SSE"),
                            ("S", "S"),
                            ("SSW", "SSW"),
                            ("SW", "SW"),
                            ("WSW", "WSW"),
                            ("W", "W"),
                            ("WNW", "WNW"),
                            ("NW", "NW"),
                            ("NNW", "NNW"),
                        ],
                        default="VRB",
                        max_length=250,
                        verbose_name="Noche",
                    ),
                ),
                (
                    "s_viento_dir_tarde",
                    models.CharField(
                        choices=[
                            ("VRB", "VRB"),
                            ("N", "N"),
                            ("NNE", "NNE"),
                            ("NE", "NE"),
                            ("ENE", "ENE"),
                            ("E", "E"),
                            ("ESE", "ESE"),
                            ("SE", "SE"),
                            ("SSE", "SSE"),
                            ("S", "S"),
                            ("SSW", "SSW"),
                            ("SW", "SW"),
                            ("WSW", "WSW"),
                            ("W", "W"),
                            ("WNW", "WNW"),
                            ("NW", "NW"),
                            ("NNW", "NNW"),
                        ],
                        default="VRB",
                        max_length=250,
                        verbose_name="Tarde",
                    ),
                ),
                (
                    "s_viento_dir_manana",
                    models.CharField(
                        choices=[
                            ("VRB", "VRB"),
                            ("N", "N"),
                            ("NNE", "NNE"),
                            ("NE", "NE"),
                            ("ENE", "ENE"),
                            ("E", "E"),
                            ("ESE", "ESE"),
                            ("SE", "SE"),
                            ("SSE", "SSE"),
                            ("S", "S"),
                            ("SSW", "SSW"),
                            ("SW", "SW"),
                            ("WSW", "WSW"),
                            ("W", "W"),
                            ("WNW", "WNW"),
                            ("NW", "NW"),
                            ("NNW", "NNW"),
                        ],
                        default="VRB",
                        max_length=250,
                        verbose_name="Mañana",
                    ),
                ),
                (
                    "s_viento_dir_noche",
                    models.CharField(
                        choices=[
                            ("VRB", "VRB"),
                            ("N", "N"),
                            ("NNE", "NNE"),
                            ("NE", "NE"),
                            ("ENE", "ENE"),
                            ("E", "E"),
                            ("ESE", "ESE"),
                            ("SE", "SE"),
                            ("SSE", "SSE"),
                            ("S", "S"),
                            ("SSW", "SSW"),
                            ("SW", "SW"),
                            ("WSW", "WSW"),
                            ("W", "W"),
                            ("WNW", "WNW"),
                            ("NW", "NW"),
                            ("NNW", "NNW"),
                        ],
                        default="VRB",
                        max_length=250,
                        verbose_name="Noche",
                    ),
                ),
                (
                    "n_viento_vel_tarde",
                    models.CharField(
                        default="VRB", max_length=100, verbose_name="Tarde"
                    ),
                ),
                (
                    "n_viento_vel_manana",
                    models.CharField(
                        default="VRB", max_length=100, verbose_name="Mañana"
                    ),
                ),
                (
                    "n_viento_vel_noche",
                    models.CharField(
                        default="VRB", max_length=100, verbose_name="Noche"
                    ),
                ),
                (
                    "i_viento_vel_tarde",
                    models.CharField(
                        default="VRB", max_length=100, verbose_name="Tarde"
                    ),
                ),
                (
                    "i_viento_vel_manana",
                    models.CharField(
                        default="VRB", max_length=100, verbose_name="Mañana"
                    ),
                ),
                (
                    "i_viento_vel_noche",
                    models.CharField(
                        default="VRB", max_length=100, verbose_name="Noche"
                    ),
                ),
                (
                    "s_viento_vel_tarde",
                    models.CharField(
                        default="VRB", max_length=100, verbose_name="Tarde"
                    ),
                ),
                (
                    "s_viento_vel_manana",
                    models.CharField(
                        default="VRB", max_length=100, verbose_name="Mañana"
                    ),
                ),
                (
                    "s_viento_vel_noche",
                    models.CharField(
                        default="VRB", max_length=100, verbose_name="Noche"
                    ),
                ),
                ("d1_fecha", models.DateField(verbose_name="Fecha")),
                ("d1_min", models.IntegerField(verbose_name="Mínima")),
                ("d1_max", models.IntegerField(verbose_name="Máxima")),
                (
                    "d1_tiempo",
                    models.CharField(
                        choices=[
                            ("PN", "PN"),
                            ("PARCN", "PARCN"),
                            ("N", "N"),
                            ("AIS CHUB", "AIS CHUB"),
                            ("ALG CHUB", "ALG CHUB"),
                            ("NUM CHUB", "NUM CHUB"),
                            ("ALG TORM", "ALG TORM"),
                            ("NUM TORM", "NUM TORM"),
                        ],
                        max_length=250,
                        verbose_name="Tiempo",
                    ),
                ),
                ("d2_fecha", models.DateField(verbose_name="Fecha")),
                ("d2_min", models.IntegerField(verbose_name="Mínima")),
                ("d2_max", models.IntegerField(verbose_name="Máxima")),
                (
                    "d2_tiempo",
                    models.CharField(
                        choices=[
                            ("PN", "PN"),
                            ("PARCN", "PARCN"),
                            ("N", "N"),
                            ("AIS CHUB", "AIS CHUB"),
                            ("ALG CHUB", "ALG CHUB"),
                            ("NUM CHUB", "NUM CHUB"),
                            ("ALG TORM", "ALG TORM"),
                            ("NUM TORM", "NUM TORM"),
                        ],
                        max_length=250,
                        verbose_name="Tiempo",
                    ),
                ),
                ("d3_fecha", models.DateField(verbose_name="Fecha")),
                ("d3_min", models.IntegerField(verbose_name="Mínima")),
                ("d3_max", models.IntegerField(verbose_name="Máxima")),
                (
                    "d3_tiempo",
                    models.CharField(
                        choices=[
                            ("PN", "PN"),
                            ("PARCN", "PARCN"),
                            ("N", "N"),
                            ("AIS CHUB", "AIS CHUB"),
                            ("ALG CHUB", "ALG CHUB"),
                            ("NUM CHUB", "NUM CHUB"),
                            ("ALG TORM", "ALG TORM"),
                            ("NUM TORM", "NUM TORM"),
                        ],
                        max_length=250,
                        verbose_name="Tiempo",
                    ),
                ),
                (
                    "fl_actual",
                    models.CharField(
                        choices=[
                            ("Luna Llena", "Luna Llena"),
                            ("Cuarto Creciente", "Cuarto Creciente"),
                            ("Cuarto Menguante", "Cuarto Menguante"),
                            ("Luna Nueva", "Luna Nueva"),
                        ],
                        max_length=250,
                        verbose_name="Actual",
                    ),
                ),
                (
                    "fl_prox",
                    models.CharField(
                        choices=[
                            ("Luna Llena", "Luna Llena"),
                            ("Cuarto Creciente", "Cuarto Creciente"),
                            ("Cuarto Menguante", "Cuarto Menguante"),
                            ("Luna Nueva", "Luna Nueva"),
                        ],
                        max_length=250,
                        verbose_name="Próxima",
                    ),
                ),
                ("fl_fecha", models.DateField(verbose_name="Fecha")),
                ("ss_actual", models.CharField(max_length=250, verbose_name="Actual")),
                (
                    "ss_prox",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Próxima"
                    ),
                ),
                (
                    "ss_fecha",
                    models.DateField(blank=True, null=True, verbose_name="Fecha"),
                ),
                ("ps_actual", models.CharField(max_length=250, verbose_name="Actual")),
                (
                    "ps_prox",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Próxima"
                    ),
                ),
                (
                    "ps_fecha",
                    models.DateField(blank=True, null=True, verbose_name="Fecha"),
                ),
                (
                    "uv_actual",
                    models.IntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Actual",
                    ),
                ),
                (
                    "uv_prox",
                    models.IntegerField(
                        blank=True,
                        default=1,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Próxima",
                    ),
                ),
                (
                    "uv_fecha",
                    models.DateField(blank=True, null=True, verbose_name="Fecha"),
                ),
                (
                    "provincia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tiempo.provincia",
                        verbose_name="Provincia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pronostico",
                "verbose_name_plural": "Pronosticos",
            },
        ),
        migrations.AddField(
            model_name="estacion",
            name="provincia",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tiempo.provincia",
                verbose_name="Provincia",
            ),
        ),
        migrations.CreateModel(
            name="Datos_adinociales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        max_length=50, verbose_name="Grupo de fenómenos especiales"
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(max_length=250, verbose_name="Descripción"),
                ),
                ("var_SpSp", models.CharField(max_length=250, verbose_name="SpSp")),
                ("var_ss", models.CharField(max_length=250, verbose_name="spsp")),
                (
                    "synop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tiempo.synop",
                        verbose_name="Synop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dato adicional",
                "verbose_name_plural": "Datos adicionales",
            },
        ),
    ]
