# Generated by Django 4.1.4 on 2023-01-16 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiempo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='synop',
            name='var_IIiii',
        ),
        migrations.RemoveField(
            model_name='synop',
            name='var_IIiii_code',
        ),
        migrations.AlterField(
            model_name='estacion',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código'),
        ),
    ]
