# Generated by Django 3.2.11 on 2022-12-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0007_auto_20221217_1137"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contacto",
            name="tipo_telefono",
            field=models.CharField(
                choices=[("Móvil", "Móvil"), ("Fijo", "Fijo")],
                default="Movil",
                max_length=250,
                verbose_name="Tipo de teléfono",
            ),
        ),
    ]
